"""change status

Revision ID: 10e1cdb33229
Revises: bc190444e40e
Create Date: 2025-04-23 21:04:04.810756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e1cdb33229'
down_revision = 'bc190444e40e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('ปกติ', 'เสีย', 'สํารอง', 'หาไม่เจอ', name='statusenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ปกติ', 'เสีย', 'สํารอง', 'หาไม่เจอ', name='statusenum'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###
