"""ff

Revision ID: 1f6cc0306288
Revises: 49be840bd644
Create Date: 2025-04-24 10:05:41.449862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6cc0306288'
down_revision = '49be840bd644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('asset_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_name', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
