"""change nullable user

Revision ID: 206fda5ad761
Revises: 10e1cdb33229
Create Date: 2025-04-23 22:00:30.825292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206fda5ad761'
down_revision = '10e1cdb33229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
