"""change nullable

Revision ID: bc190444e40e
Revises: 
Create Date: 2025-04-23 20:50:15.086836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc190444e40e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('asset_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('brand',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('asset_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cpu_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('cpu_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('ram',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('ram_memory',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('mainboard_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('mainboard_model',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('ssd',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('ssd_model',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('hdd',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('hdd_model',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('gpu',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('powersupply',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('os',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('os',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('powersupply',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('gpu',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('hdd_model',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('hdd',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('ssd_model',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('ssd',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('mainboard_model',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('mainboard_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('ram_memory',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ram',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('cpu_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('cpu_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('asset_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('brand',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('asset_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
